layouts/_default/baseof.html, layouts/partials/ama.html
=> Add AMA banner

layouts/_default/baseof.html, layouts/partials/ama.html
This reverts commit a8b21af63f52c6a60a5010519a65e0759ee65e3e.
=> Revert "Add AMA banner. Enable at 3PM EST Oct. 25th"

i18n/de.yaml, i18n/en.yaml
Everything is translated to German, including the latest changes.
=> Added German translation

config.toml, content/about/index.de.html, content/about/milestones.de.html, content/apps.de.html, content/faq.de.html, content/get-siacoin.de.html, content/get-started.de.html, content/index.de.html
and *.de.html symlinks
Thanks to @betaboot for PR #62 that added the German translations.
=> Add German to config

content/gauntlet.html
https://blockchainedu.org/gauntlet/
live at https://sia.tech/gauntlet
=> Add gauntlet page for the blockchain gauntlet hackathon

content/jobs.html
Changes are live on http://staging.sia.tech/jobs
=> add jobs page

content/brand.html
Changes are live at http://staging.sia.tech/brand/
=> replace colors image with colors html markup

content/jobs.html
lighting network -> lightning network
=> fix `lightning network` typo on jobs page

content/apps.html, content/lts.html, i18n/en.yaml
These changes are live on the main site.
=> add LTS releases and update apps page to 1.0.4

build.sh
These pages are aliases of the /apps page.
Changes are live http://staging.sia.tech.
=> add /download, /downloads page

content/about/milestones.html, content/apps.html
this PR updates the /apps page to include links to the new v1.1.0 release, and updates the roadmap with the completed speed boost milestone.
=> update website with v1.1.0

content/lts.html, i18n/de.yaml, i18n/en.yaml, i18n/fr.yaml, i18n/ru.yaml, i18n/zh-hans.yaml, i18n/zh-hant.yaml
changes are live on http://staging.sia.tech
=> update Sia-UI and Sia Daemon titles to include (LTS) on lts page

content/apps.html
This PR is running on production already.
=> update with new v1.1.2 release

i18n/fr.yaml
One of our users in slack pointed out some mistakes in the french homepage translation, this PR corrects them.
Currently live on staging.sia.tech.
=> correct french translation

build.sh, config.toml, i18n/en.yaml, i18n/ha.yaml
this PR adds hebrew translations provided by our contributor Shay. Currently only the homepage is translated, changes are live on https://staging.sia.tech.
=> add hebrew translations

content/faq.html, i18n/en.yaml
FAQs updated and simplified. English translation included. Still need to get other translations. Might also want to remove the collapse function due to low number of FAQs.
=> FAQ Updates

layouts/partials/footer.html, layouts/partials/header.html, static/css/style-homepage.css
Updated header to add a new dropdown called Resources. Rearranged some
items from the Community dropdown. Changed the dropdown width. Changed
the padding on the language dropdown. Edited Footer to have Roadmap
open in a new tab.
=> Updated Header and Footer

content/apps.html
this is already running on https://sia.tech
=> update download links with 1.2.0 release

content/apps.html
=> update download links to v1.2.1

i18n/fr.yaml
"Agriculturer" is not a French word.
=> Correct term for farming

content/get-siacoin.html, i18n/en.yaml
Fixed Bittrex description — was previously pointed at Shapeshift. Also
adjusted description.
=> Fixes to Bittrex description

content/2017grant.html
New page for announcement of INBlockchain grant
=> Announcement of INBlockchain grant

content/get-siacoin.html
=> Remove Yunbi
